// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKNu-nPfGBmB5LHgvNKj3QsO4gh95TxN0',
    appId: '1:393876330198:web:6f5d4ea5d3298adf609b77',
    messagingSenderId: '393876330198',
    projectId: 'project-gaia-d7b6e',
    authDomain: 'project-gaia-d7b6e.firebaseapp.com',
    databaseURL: 'https://project-gaia-d7b6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-gaia-d7b6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7eapz6zfVkXo4ITafZSdQuhwQ7__g_SA',
    appId: '1:393876330198:android:7ba45fee43c63197609b77',
    messagingSenderId: '393876330198',
    projectId: 'project-gaia-d7b6e',
    databaseURL: 'https://project-gaia-d7b6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-gaia-d7b6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCma9ESGC0cU40KykKYnraRKjGrBJt2uFo',
    appId: '1:393876330198:ios:10adeaa26da1fa38609b77',
    messagingSenderId: '393876330198',
    projectId: 'project-gaia-d7b6e',
    databaseURL: 'https://project-gaia-d7b6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-gaia-d7b6e.firebasestorage.app',
    iosBundleId: 'com.example.projectGaia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCma9ESGC0cU40KykKYnraRKjGrBJt2uFo',
    appId: '1:393876330198:ios:10adeaa26da1fa38609b77',
    messagingSenderId: '393876330198',
    projectId: 'project-gaia-d7b6e',
    databaseURL: 'https://project-gaia-d7b6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-gaia-d7b6e.firebasestorage.app',
    iosBundleId: 'com.example.projectGaia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKNu-nPfGBmB5LHgvNKj3QsO4gh95TxN0',
    appId: '1:393876330198:web:44289433bafcf80f609b77',
    messagingSenderId: '393876330198',
    projectId: 'project-gaia-d7b6e',
    authDomain: 'project-gaia-d7b6e.firebaseapp.com',
    databaseURL: 'https://project-gaia-d7b6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-gaia-d7b6e.firebasestorage.app',
  );

}